"use client";
import {useState} from "react";
import {PDFDownloadLink,Document,Page,Text,View,StyleSheet} from "@react-pdf/renderer";

const initial={
academicYear:"2026-27",quarter:"Q1",title:"",date:"",duration:"",mode:"Offline",
venue:"",category:"IIC Calendar Activity",objectives:"",attendance:"",ledBy:"Institute Council",
department:"Computer Science & Engineering",theme:"",expertName:"",expertDesignation:"",
expertOrg:"",expertBrief:"",hod:"",eventCoordinator:"",faculty:"",description:"",
students:"",staff:"",external:"",po:"",pso:"",highlights:"",outcome:"",feedback:"",
preSocial:"",postSocial:"",drive:""
};

const pdfStyles=StyleSheet.create({
 page:{padding:32,fontFamily:"Helvetica",fontSize:9,color:"#111"},
 border:{border:"1pt solid #111",padding:18,minHeight:760},
 header:{textAlign:"center",marginBottom:14,borderBottom:"1pt solid #222",paddingBottom:8},
 college:{fontSize:14,fontWeight:"bold"},sub:{fontSize:8,marginTop:3},title:{fontSize:10,fontWeight:"bold",marginTop:5},
 section:{fontSize:10,fontWeight:"bold",marginTop:10,marginBottom:5},
 row:{flexDirection:"row",borderBottom:"1pt solid #444"},label:{width:"42%",padding:4,fontWeight:"bold"},val:{width:"58%",padding:4},
 box:{border:"1pt solid #333",padding:7,minHeight:55,lineHeight:1.4}
});
function Header({d}){return <View style={pdfStyles.header}><Text style={pdfStyles.college}>NMAM INSTITUTE OF TECHNOLOGY, NITTE</Text><Text style={pdfStyles.sub}>INSTITUTION'S INNOVATION COUNCIL (IIC)</Text><Text style={pdfStyles.sub}>IIC ACTIVITY REPORT</Text><Text style={pdfStyles.title}>Academic Year: {d.academicYear}   Quarter: {d.quarter}</Text></View>}
function PDFReport({d}){let rows=[["Academic Year",d.academicYear],["Quarter",d.quarter],["Title of the session",d.title],["Date with Month & Year",d.date],["Duration (in hours)",d.duration],["Mode",d.mode],["Venue / Platform",d.venue],["Activity Category",d.category],["Session Objectives",d.objectives],["Attendance Link",d.attendance],["Activity Led by",d.ledBy],["Organizing Department",d.department],["Theme",d.theme]];
return <Document><Page size="A4" style={pdfStyles.page}><View style={pdfStyles.border}><Header d={d}/><Text style={pdfStyles.section}>SESSION DETAILS</Text>{rows.map((r,i)=><View style={pdfStyles.row} key={i}><Text style={pdfStyles.label}>{i+1}. {r[0]}</Text><Text style={pdfStyles.val}>{r[1]||"—"}</Text></View>)}<Text style={pdfStyles.section}>EXPERT / SPEAKER DETAILS</Text>{[["Name",d.expertName],["Designation",d.expertDesignation],["Organization / Institution",d.expertOrg],["Brief about Expert",d.expertBrief]].map((r,i)=><View style={pdfStyles.row} key={i}><Text style={pdfStyles.label}>{i+1}. {r[0]}</Text><Text style={pdfStyles.val}>{r[1]||"—"}</Text></View>)}</View></Page>
<Page size="A4" style={pdfStyles.page}><View style={pdfStyles.border}><Header d={d}/><Text style={pdfStyles.section}>ORGANIZING TEAM DETAILS</Text><View style={pdfStyles.box}><Text>Head of Department: {d.hod||"—"}</Text><Text>Event Coordinator: {d.eventCoordinator||"—"}</Text><Text>Faculty Coordinators: {d.faculty||"—"}</Text></View><Text style={pdfStyles.section}>BRIEF DESCRIPTION OF THE ACTIVITY</Text><View style={[pdfStyles.box,{minHeight:560}]}><Text>{d.description||"—"}</Text></View></View></Page>
<Page size="A4" style={pdfStyles.page}><View style={pdfStyles.border}><Header d={d}/><Text style={pdfStyles.section}>PARTICIPANT METRICS</Text>{[["Students",d.students],["Staff",d.staff],["External",d.external]].map((r,i)=><View style={pdfStyles.row} key={i}><Text style={pdfStyles.label}>{r[0]}</Text><Text style={pdfStyles.val}>{r[1]||"0"}</Text></View>)}<Text style={pdfStyles.section}>MAPPING</Text><View style={pdfStyles.row}><Text style={pdfStyles.label}>PO Mapped</Text><Text style={pdfStyles.val}>{d.po||"—"}</Text></View><View style={pdfStyles.row}><Text style={pdfStyles.label}>PSO Mapped</Text><Text style={pdfStyles.val}>{d.pso||"—"}</Text></View><Text style={pdfStyles.section}>KEY HIGHLIGHTS</Text><View style={pdfStyles.box}><Text>{d.highlights||"—"}</Text></View><Text style={pdfStyles.section}>OUTCOME OF THE ACTIVITY</Text><View style={pdfStyles.box}><Text>{d.outcome||"—"}</Text></View><Text style={pdfStyles.section}>FEEDBACK SUMMARY</Text><View style={pdfStyles.box}><Text>{d.feedback||"—"}</Text></View><Text style={pdfStyles.section}>SOCIAL MEDIA / EVIDENCE</Text><View style={pdfStyles.box}><Text>Pre-Activity: {d.preSocial||"—"}</Text><Text>Post-Activity: {d.postSocial||"—"}</Text><Text>Multimedia: {d.drive||"—"}</Text></View></View></Page>
<Page size="A4" style={pdfStyles.page}><View style={pdfStyles.border}><Header d={d}/><Text style={[pdfStyles.section,{textAlign:"center"}]}>SESSION VISUAL PROOFS</Text><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{[1,2,3,4].map(i=><View key={i} style={{width:"48%",height:220,border:"1pt solid #333",padding:6}}><Text>ACTION PHOTO {i}</Text></View>)}</View><Text style={pdfStyles.section}>MULTIMEDIA CONTENT LINK</Text><View style={pdfStyles.box}><Text>{d.drive||"—"}</Text><Text style={{marginTop:10}}>QR code can be added to the final production version.</Text></View><View style={{flexDirection:"row",justifyContent:"space-between",marginTop:80}}><Text>EVENT COORDINATOR{"\n"}{d.eventCoordinator||""}</Text><Text>DEPT. IIC COORDINATOR{"\n"}{d.eventCoordinator||""}</Text><Text>HOD{"\n"}{d.hod||""}</Text></View></View></Page></Document>}

export default function Home(){
 const [logged,setLogged]=useState(false),[user,setUser]=useState(""),[pass,setPass]=useState(""),[view,setView]=useState("dashboard"),[d,setD]=useState(initial),[saved,setSaved]=useState([]);
 const update=(k,v)=>setD(x=>({...x,[k]:v}));
 if(!logged)return <main className="login"><div className="loginCard"><div className="logoCircle">IIC</div><h1>NMAMIT IIC</h1><p>Institution's Innovation Council</p><input placeholder="Coordinator Username" value={user} onChange={e=>setUser(e.target.value)}/><input placeholder="Password" type="password" value={pass} onChange={e=>setPass(e.target.value)}/><button onClick={()=>setLogged(true)}>LOGIN</button><small>Demo login: enter any username and password.</small></div></main>;
 const fields=[
 ["academicYear","Academic Year"],["quarter","Quarter"],["title","Title of the Session"],["date","Date"],["duration","Duration (hours)"],["mode","Mode"],["venue","Venue / Platform"],["category","Activity Category"],["objectives","Session Objectives"],["attendance","Attendance Link"],["ledBy","Activity Led By"],["department","Organizing Department"],["theme","Theme"],["expertName","Expert Name"],["expertDesignation","Expert Designation"],["expertOrg","Expert Organization"],["expertBrief","Brief About Expert"],["hod","Head of Department"],["eventCoordinator","Event Coordinator"],["faculty","Faculty Coordinators"],["description","Brief Description"],["students","Student Participants"],["staff","Staff Participants"],["external","External Participants"],["po","PO Mapped"],["pso","PSO Mapped"],["highlights","Key Highlights"],["outcome","Outcome"],["feedback","Feedback Summary"],["preSocial","Pre-Activity Social Link"],["postSocial","Post-Activity Social Link"],["drive","Multimedia / G-Drive Link"]];
 return <div className="shell"><aside><div className="brand">NMAMIT <span>IIC</span></div><div className="user">Coordinator<br/><b>{user}</b></div><button className="nav active" onClick={()=>setView("dashboard")}>Dashboard</button><button className="nav" onClick={()=>setView("new")}>＋ Create Report</button><button className="nav" onClick={()=>setView("reports")}>▣ My Reports</button><button className="logout" onClick={()=>setLogged(false)}>Logout</button></aside><section className="main"><div className="top"><div><h2>{view==="dashboard"?"Dashboard":view==="new"?"Create IIC Report":"My Reports"}</h2><p>NMAM Institute of Technology, Nitte</p></div></div>{view==="dashboard"&&<div className="dash"><div className="cards"><div><b>+ NEW REPORT</b><span>Create a new IIC activity report</span><button onClick={()=>setView("new")}>Create Report</button></div><div><b>MY REPORTS</b><span>{saved.length} saved reports</span><button onClick={()=>setView("reports")}>View Reports</button></div></div><div className="info"><h3>Report workflow</h3><p>Enter details → upload evidence → preview → generate ready PDF.</p></div></div>}{view==="reports"&&<div className="table">{saved.length===0?<p>No reports saved yet.</p>:saved.map((r,i)=><div className="reportRow" key={i}><b>{r.title||"Untitled Report"}</b><span>{r.date}</span><button onClick={()=>{setD(r);setView("new")}}>Edit</button></div>)}</div>}{view==="new"&&<div className="builder"><div className="form">{fields.map(([k,l])=><label key={k}>{l}{["objectives","expertBrief","faculty","description","highlights","outcome","feedback"].includes(k)?<textarea value={d[k]} onChange={e=>update(k,e.target.value)}/>:<input value={d[k]} onChange={e=>update(k,e.target.value)}/>}</label>)}<div className="btns"><button onClick={()=>{setSaved(s=>[...s.filter(x=>x.title!==d.title),d]);alert("Report saved.")}}>SAVE DRAFT</button><PDFDownloadLink document={<PDFReport d={d}/>} fileName={(d.title||"NMAMIT-IIC-Report").replace(/[^a-z0-9]+/gi,"-")+".pdf"}><button className="primary">GENERATE & DOWNLOAD PDF</button></PDFDownloadLink></div></div><div className="preview"><div className="previewHead">LIVE REPORT PREVIEW</div><div className="sheet"><h3>NMAM INSTITUTE OF TECHNOLOGY, NITTE</h3><p>INSTITUTION'S INNOVATION COUNCIL (IIC)</p><h4>IIC ACTIVITY REPORT</h4><b>SESSION DETAILS</b>{fields.slice(0,13).map(([k,l])=><div className="pv" key={k}><strong>{l}</strong><span>{d[k]||"—"}</span></div>)}<b>EXPERT / SPEAKER DETAILS</b>{fields.slice(13,17).map(([k,l])=><div className="pv" key={k}><strong>{l}</strong><span>{d[k]||"—"}</span></div>)}</div></div></div>}</section></div>
}
